server:
  port: 8182 
 
spring:
  application:
    name: oscar_oliveira
  profiles: # dev ou prod (${spring_profile})
    active: prod   
    
propriedades:
  aplicacao:
    nome: "@project.artifactId@"
    versao: "@project.version@"
    descricao: "@project.description@"
    messageSource: messages

springdoc:
  packagesToScan: br.com.infnet
  swagger-ui:
    path: /swagger/ui
    enabled: true
  api-docs:
    path: /swagger/json
    enabled: true    
    
    
# Configurações específicas para perfis
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod